### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by sinfulz** [prajwalsingh/OpenCv-Morse-Code-Solver#1]
Hi,

This does not work at all. I used your example image(s) to try and convert Morse Code to alphabet characters and the program opened the image with the Morse Code. It did no converting at all.

Thanks

**Comment by prajwalsingh** [comment]
This works if you write your morse code in the way given in sample images. Use the marker to write, because the algorithm I have used is based on the fact that Line will contain more than 30 white pixels and Circle will contain white pixels between 10 to 29.
This may not work if we try to convert morse code written using normal pen ink.
